version: '3.3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # Create a Database User so I don't have to use root
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where data will be persisted
    volumes:
      - weddings-db:/var/lib/mysql
    
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
# Names the volume
volumes:
  weddings-db:
  